### ISSUE TITLE
Support UDFs

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/mapd-core#2]
We can use this issue to make a plan to support row level UDFs

**Comment by saulshanabrook** [comment]
Code links:

* How does MapD core store a column of data? This is how it applies an aggregate: https://github.com/mapd/mapd-core/blob/4caaabaf25f4c0e7313a4fdc511f984dcd6346ae/QueryEngine/Execute.cpp#L550

Plan:

1. User registers UDF. We compile python function with Numba matching python type annotations to Numba types that correspond to how MapD holds each of these data types in memory (should be straightforward for primitive int/float types, will need to look  into this for list types)
2. Send this compiled function to MapD backend. How? We can [get pointer to compiled Numba function](https://github.com/Quansight/numba-xnd/blob/9a914ea76442385ada1940bde963a14faad9dee3/numba_xnd/gumath.py#L199) and maybe get it's size as well? Can we then just serialize those bytes? (maybe this won't work since machines are different?) Alternative is to compile on the mapd server...
3. Add global mapping in MapD server of UDF name to types and function pointer. Maybe we also save serialized functions in system table in database? Then when server starts, it builds global table in memory of functions? And when we add a function it adds to database as well as adding in memory?
4. Add custom parsing logic in Calcite that looks in global registry of UDFs.
5. To execute UDF, we call function on data. We copy data first. We could call in CPU or in GPU. If in GPU, need to explore compiling to GPU in Numba and how we call that function.
6. Figure out where to plug in result of call

**Comment by saulshanabrook** [comment]
First steps:

1. Add custom function written in C++ in mapd core and see if we can register with query parser and get it to execute properly on GPU and CPU.
2. Compile same function with Numba and see how to ship this to backend and call it.

**Comment by saulshanabrook** [comment]
Think it makes more sense to compile shared library on client and send to server, then trying to send serialized function in memory. See http://numba.pydata.org/numba-doc/latest/user/pycc.html for how to compile shared library with Numba

**Comment by saulshanabrook** [comment]
Seems like we have a choice of what to send over the wire. In order from closeness to user input:

1. Python source as string
2. Python AST
3. Python bytecode
4. Numba IR
5. LLVM IR
6. machine code (as library file)

**Comment by saulshanabrook** [comment]
Our most recent plan is to send Python source over to the server somehow. Then we use embedded Python (w/ Numba installed) to take python string and get out function pointer as integer. Then we call that function pointer from C++ in the mapd server. We have to define our own protocol / ABI for how we compile the UDFs in Numba to match how we call them in C++ (see [example from gumath numba](https://github.com/Quansight/numba-xnd/blob/9a914ea76442385ada1940bde963a14faad9dee3/numba_xnd/gumath.py#L158-L199)).

**Comment by saulshanabrook** [comment]
# Approaches

We prefer using numba to compile on the server.


## Compile on the client

In this setup the user has numba installed in their python environment along with the mapd client.
When they annotate a function to be compiled as a UDF we use numba locally compile that function to  machine code. We send that to the server where it is loaded into memory as a function and called when needed.

Since we [can't use arbitrary memory as a function](https://stackoverflow.com/questions/37330620/serialize-a-function-in-c/37331169#37331169), we could send a shared library over the wire instead of just the function bytes 

### Pros
* No need for numba, python or other compilation infrastructure on the server
* Numba is being run on the same machine where the UDFs are defined, so if a user references other Python code in their UDF, numba will know how to compile that too. 

### Cons
* Hard to secure, server is being sent and running arbitrary machine code
* Would need to investigate how to use [clang's cross compilation](https://clang.llvm.org/docs/CrossCompilation.html) in Numba (doesn't seem to be supported out of the box). This is required if server is running different CPU than client.

## Compile on Server
With this approach we send a string of Python UDF source to the server. We would run Python embedded in the server and compile the UDFs when the server starts up or when it receives a new one. We would get a function pointer back from the embedded python and call that in C++ to apply the UDF.

### Pros
* compiling there where the code will be run, should be more robust. Don't need to figure out how/if cross compiling works in Numba
* Seems easier to secure, i.e. could add limits to Numba compilation to disallow certain forms or have a whitelist of only certain things to allow that would be enforced server side
* Don't need to figure out how to serialize compiled function, we can just compile it on the server when we need it and cache it.

### Cons
* Need to figure out how to best ship UDF as python string to server. Requires more work to support calling other Python functions or library calls from it.
* Source and target python version might not be the same, meaning valid syntax in one would be invalid in the other.

**Comment by saulshanabrook** [comment]
Venkat mentioned that MapD already has some sort of UDF called "Extension Functions". I found this file https://github.com/omnisci/mapd-core/blob/master/QueryEngine/ExtensionFunctions.hpp 

It looks like you define a function and then you can use it in SQL? It might be possible for us to compile UDFs to be implemented as extension functions.

**Comment by pearu** [comment]
The extension functions feature can be used for implementing UDFs indeed. To most straightforward approach would be to define an extension function, say APPLY, that takes two arguments, a function name and some container of arguments, that inside the APPLY C++ function are passed to external library or program, say Python, that evaluates the function with given arguments in the external program and returns the results to APPLY. The APPLY C++ has to just take care of the arguments and the results conversations when these are not compatible with the corresponding data types in C++.
